### ISSUE TITLE
Vk.com support

### ISSUE THREAD

**Issue by legenda864** [OmarElGabry/Hashtegny#1]
Hi there,
I am so glad that I found your Hashtegny..It works perfect and looks great
I think it has big potential..And I would like to ask you to add support for social web http://vk.com
 It is also very popular in many countries and has some features like music, video etc. It has own API for developers..So I hope you can
If you have any questions about that feel free to ask me about
Thank you

**Comment by OmarElgabry** [comment]
Hello!,
Thank you, I went through the API Documentation and I found it's doable and easy. I will add it to my future plans as well as some enhancements to the Plugin.
If you have any other suggestions feel free to send me, I will be more than glad.

Regards,

**Comment by legenda864** [comment]
Oh, its great news!
Hope you can also add cyrillic symbols support, because now it works only for a-z etc. But every social network already support for win-1251 like cyrillic
Thank you

**Comment by OmarElgabry** [comment]
Ok, I will check this as well. Thank you

**Comment by legenda864** [comment]
Hi
Is there any news about vk api integration?

**Comment by OmarElgabry** [comment]
Hey, 
I am really sorry for that, I've been working on my graduation project which is a web based application for my university, it's very hectic :smile: 

I will do it as soon as i finish it. However, if you want to integrate vk.com as soon as possible, maybe you will be using the plugin, or for your personal uses, I can do it this week, no problem.

I am planning to do a lot of enhancement to this plugin as well as adding new plugins, but, for now, it's really hard for me to compromise with my studies

Waiting to hear from you

**Comment by legenda864** [comment]
Ok, I am very interested in your project and plan to donate it
And Vk.com integration + cyrillic symbols are very important for me to
start use it in real time
Now It looks great, but useless without vk and cyrillic
Thank you

Ps If you are interested in donations for your work BitCoin wallet
appreciated to make it from me

2014-12-10 15:13 GMT+00:00 Omar El Gabry notifications@github.com:

**Comment by OmarElgabry** [comment]
I added the support for vk.com, as well as you can enter Cyrillic letters as you can see below.
Check it, and let me know 

![capture](https://cloud.githubusercontent.com/assets/9262504/5404229/5f0fa8a2-819d-11e4-8292-b64920c3302c.PNG)

![capture1](https://cloud.githubusercontent.com/assets/9262504/5404264/e258a588-819d-11e4-9eaa-782786435c28.PNG)

**Comment by legenda864** [comment]
Hi, Omar
Vk.com support works amazing!
Just some questions:
1.How can I enable/disable G+ for example? Now if I delete input form for
G+, it search G+ too.
2. How can I change order for show. I would like to show VK tags firstly
3. Is it possible to make pause on mouse hover for tag and continue after
hover out?
4.Can I donate your work? May be you have Btc wallet?
Thank you

2014-12-11 23:29 GMT+00:00 Omar El Gabry notifications@github.com:

**Comment by legenda864** [comment]
Also would be nice to make profiles or posts clickable

2014-12-13 18:54 GMT+00:00 Anton Esaulov legenda864@gmail.com:

**Comment by OmarElgabry** [comment]
Hello Again,
1. To disable any one(whether G+ or any), leave the input empty, if it's empty it won't get any posts. I am sure it won't search unless there is a text inside. Try to leave it empty and if you faced any issue let me know
2. The Posts are ordered according to the timestamp; the time they were posted in. I can do it for you, it's easier to order the posts by the type of the social network rather than the time stamp
3. Yes, Definitely, But, I made this animation for a specific purpose which is, you can have a projector or a data show, or even TV, and the posts will be displayed one after another so the audience can enjoy the way the posts while they are animating without any interference from the user(like hover and so on). But, it's doable, no problem
4. Unfortunately I don't have one, Thank you so much, i am doing this for free, even if you need to add extra features, i will make it for you. But, Honestly speaking i am little bit busy these days, i am still a student at the last year of graduation. Maybe in my free time i will try to add these features one after another.
5. Posts and Profiles can be clickable But, again, this is out of the scope of the main purpose of the idea of the plugin. As i don't need any user interactions from hovering over the posts or clicking the posts. But, as usual i can do it, no problems.

Thanks

**Comment by legenda864** [comment]
Ok, Omar
Please, let me know the way to make posts (and/or profiles) clickable and
pause on hover
Also, it might be easier to interact with navigation for slides (<left
right>)

Hope in the future you can also add search for keywords and vk.com/groups.
So Admin can search special area (like special groups) of social web

2014-12-13 22:30 GMT+00:00 Omar El Gabry notifications@github.com:

**Comment by OmarElgabry** [comment]
The data that's sent from any social media channel like vk.com is sent as JSON. It has all the info including the link to the post and profiles. All what you need is to grab these links and put it into your web page. 
The posts are displayed one after another by time interval(every 8sec by default). All what you need is to set an event that tells the code; Whenever the user hover over the post, pause the animation of the post, and whenever the user gets the mouse out of the post area, resume the animation.

For interaction with slides, you have two options, either remove the animation of the posts, and you will have the full control over the posts. So, you can navigate between them
Or, you can have the animation between posts, and also there will be slides(<left right>). So, whenever you hit left or right, it will navigate between the posts, and then resume the animation again until the next interaction

It's quite simple, I don't have specific way of implementation now in my mind, because it could be done in a various ways

**Comment by legenda864** [comment]
Can you write 1 example for vk.com to implement link for post and profile
automatically to make it clickable?

2014-12-15 19:42 GMT+00:00 Omar El Gabry notifications@github.com:
